/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kase.aptechsaigon.projectsem2;

import javax.swing.JFrame;

/**
 *
 * @author Moiiii
 */
public class InfoAcc extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public InfoAcc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAcc = new javax.swing.JMenu();
        mnuiViewAcc = new javax.swing.JMenuItem();
        mnuiEditAcc = new javax.swing.JMenuItem();
        mnuHR = new javax.swing.JMenu();
        mnuDepartment = new javax.swing.JMenu();
        mnuiViewDept = new javax.swing.JMenuItem();
        mnuiAddDept = new javax.swing.JMenuItem();
        mnuiEditDept = new javax.swing.JMenuItem();
        mnuiDelDept = new javax.swing.JMenuItem();
        mnuTeam = new javax.swing.JMenu();
        mnuiViewStaff1 = new javax.swing.JMenuItem();
        mnuiAddStaff1 = new javax.swing.JMenuItem();
        mnuiEditStaff1 = new javax.swing.JMenuItem();
        mnuiDeleteStaff1 = new javax.swing.JMenuItem();
        mnuStaff = new javax.swing.JMenu();
        mnuiViewStaff = new javax.swing.JMenuItem();
        mnuiAddStaff = new javax.swing.JMenuItem();
        mnuiEditStaff = new javax.swing.JMenuItem();
        mnuiDeleteStaff = new javax.swing.JMenuItem();
        mnuSalary = new javax.swing.JMenu();
        mnuiViewSalary = new javax.swing.JMenuItem();
        mnuiCalSalaray = new javax.swing.JMenuItem();
        mnuJob = new javax.swing.JMenu();
        mnuJobList = new javax.swing.JMenuItem();
        mnuJobAssignment = new javax.swing.JMenuItem();
        mnuTaskManagement = new javax.swing.JMenuItem();
        mnuTaskReport = new javax.swing.JMenuItem();
        mnuStatistical = new javax.swing.JMenu();
        mnuiS_Salary = new javax.swing.JMenuItem();
        mnuiS_Job = new javax.swing.JMenuItem();
        mnuiS_HR = new javax.swing.JMenuItem();
        mnuSystem = new javax.swing.JMenu();
        mnuiInfo = new javax.swing.JMenuItem();
        mnuiLogout = new javax.swing.JMenuItem();
        mnuiExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã nhân viên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Họ và tên nhân viên");

        jLabel5.setText("Ngày tháng năm sinh:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("DD/MM/YY");

        jLabel7.setText("CCCD:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("###########");

        jLabel9.setText("Địa chỉ:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Thông tin địa chỉ");

        jLabel11.setText("Email:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Thông tin email");

        jLabel13.setText("Thời hạn hợp đồng");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("DD/MM/YY");

        jLabel15.setText("Ngày bắt đầu làm việc");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("DD/MM/YY");

        jLabel17.setText("Kinh nghiệm");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("x Năm");

        jLabel19.setText("Mật khẩu");

        jLabel21.setText("Vị trí");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("****************");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Tên vị trí");

        jLabel23.setText("Tên tài khoản");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Tên đăng nhập ở đây");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        mnuAcc.setText("Tài khoản");

        mnuiViewAcc.setText("Xem thông tin");
        mnuAcc.add(mnuiViewAcc);

        mnuiEditAcc.setText("Chỉnh sửa");
        mnuAcc.add(mnuiEditAcc);

        jMenuBar1.add(mnuAcc);

        mnuHR.setText("Nhân sự");

        mnuDepartment.setText("Phòng ban");

        mnuiViewDept.setText("Xem danh sách phòng ban");
        mnuDepartment.add(mnuiViewDept);

        mnuiAddDept.setText("Thêm phòng ban");
        mnuDepartment.add(mnuiAddDept);

        mnuiEditDept.setText("Điều chỉnh phòng ban");
        mnuDepartment.add(mnuiEditDept);

        mnuiDelDept.setText("Xóa thông tin nhân viên");
        mnuDepartment.add(mnuiDelDept);

        mnuHR.add(mnuDepartment);

        mnuTeam.setText("Nhóm");

        mnuiViewStaff1.setText("Xem danh sách nhóm");
        mnuTeam.add(mnuiViewStaff1);

        mnuiAddStaff1.setText("Thêm nhóm");
        mnuTeam.add(mnuiAddStaff1);

        mnuiEditStaff1.setText("Điều chỉnh thông tin nhóm");
        mnuiEditStaff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiEditStaff1ActionPerformed(evt);
            }
        });
        mnuTeam.add(mnuiEditStaff1);

        mnuiDeleteStaff1.setText("Xóa nhóm");
        mnuTeam.add(mnuiDeleteStaff1);

        mnuHR.add(mnuTeam);

        mnuStaff.setText("Nhân viên");

        mnuiViewStaff.setText("Xem danh sách nhân viên");
        mnuStaff.add(mnuiViewStaff);

        mnuiAddStaff.setText("Thêm nhân viên");
        mnuStaff.add(mnuiAddStaff);

        mnuiEditStaff.setText("Điều chỉnh thông tin nhân viên");
        mnuStaff.add(mnuiEditStaff);

        mnuiDeleteStaff.setText("Xóa thông tin nhân viên");
        mnuStaff.add(mnuiDeleteStaff);

        mnuHR.add(mnuStaff);

        mnuSalary.setText("Lương");

        mnuiViewSalary.setText("Xem bảng lương");
        mnuSalary.add(mnuiViewSalary);

        mnuiCalSalaray.setText("Tính lương");
        mnuSalary.add(mnuiCalSalaray);

        mnuHR.add(mnuSalary);

        jMenuBar1.add(mnuHR);

        mnuJob.setText("Công việc");

        mnuJobList.setText("Danh sách công việc");
        mnuJob.add(mnuJobList);

        mnuJobAssignment.setText("Phân công công việc");
        mnuJob.add(mnuJobAssignment);

        mnuTaskManagement.setText("Quản lý nhiệm vụ");
        mnuJob.add(mnuTaskManagement);

        mnuTaskReport.setText("Báo cáo nhiệm vụ");
        mnuJob.add(mnuTaskReport);

        jMenuBar1.add(mnuJob);

        mnuStatistical.setText("Thống kê");

        mnuiS_Salary.setText("Thống kê công việc");
        mnuStatistical.add(mnuiS_Salary);

        mnuiS_Job.setText("Thống kê nhân sự");
        mnuStatistical.add(mnuiS_Job);

        mnuiS_HR.setText("Thống kê lương");
        mnuStatistical.add(mnuiS_HR);

        jMenuBar1.add(mnuStatistical);

        mnuSystem.setText("Hệ thống");

        mnuiInfo.setText("Thông tin ứng dụng");
        mnuSystem.add(mnuiInfo);

        mnuiLogout.setText("Đăng xuất");
        mnuSystem.add(mnuiLogout);

        mnuiExit.setText("Thoát chương trình");
        mnuSystem.add(mnuiExit);

        jMenuBar1.add(mnuSystem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiEditStaff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiEditStaff1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiEditStaff1ActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    try {
        // Set the Nimbus look and feel
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(InfoAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Create and display the Login form first
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Login loginFrame = new Login(); // Hiển thị cửa sổ Login đầu tiên
            loginFrame.setVisible(true); // Hiển thị cửa sổ Login
        }
    });
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuAcc;
    private javax.swing.JMenu mnuDepartment;
    private javax.swing.JMenu mnuHR;
    private javax.swing.JMenu mnuJob;
    private javax.swing.JMenuItem mnuJobAssignment;
    private javax.swing.JMenuItem mnuJobList;
    private javax.swing.JMenu mnuSalary;
    private javax.swing.JMenu mnuStaff;
    private javax.swing.JMenu mnuStatistical;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenuItem mnuTaskManagement;
    private javax.swing.JMenuItem mnuTaskReport;
    private javax.swing.JMenu mnuTeam;
    private javax.swing.JMenuItem mnuiAddDept;
    private javax.swing.JMenuItem mnuiAddStaff;
    private javax.swing.JMenuItem mnuiAddStaff1;
    private javax.swing.JMenuItem mnuiCalSalaray;
    private javax.swing.JMenuItem mnuiDelDept;
    private javax.swing.JMenuItem mnuiDeleteStaff;
    private javax.swing.JMenuItem mnuiDeleteStaff1;
    private javax.swing.JMenuItem mnuiEditAcc;
    private javax.swing.JMenuItem mnuiEditDept;
    private javax.swing.JMenuItem mnuiEditStaff;
    private javax.swing.JMenuItem mnuiEditStaff1;
    private javax.swing.JMenuItem mnuiExit;
    private javax.swing.JMenuItem mnuiInfo;
    private javax.swing.JMenuItem mnuiLogout;
    private javax.swing.JMenuItem mnuiS_HR;
    private javax.swing.JMenuItem mnuiS_Job;
    private javax.swing.JMenuItem mnuiS_Salary;
    private javax.swing.JMenuItem mnuiViewAcc;
    private javax.swing.JMenuItem mnuiViewDept;
    private javax.swing.JMenuItem mnuiViewSalary;
    private javax.swing.JMenuItem mnuiViewStaff;
    private javax.swing.JMenuItem mnuiViewStaff1;
    // End of variables declaration//GEN-END:variables
}
